allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: false
  unix-dgram: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.3'
  - '@better-auth/drizzle-adapter@1.7.3'
  - '@better-auth/kysely-adapter@1.7.3'
  - '@better-auth/memory-adapter@1.7.3'
  - '@better-auth/mongo-adapter@1.7.3'
  - '@better-auth/prisma-adapter@1.7.3'
  - '@better-auth/telemetry@1.7.3'
  - better-auth@1.7.3
