name: 📄  Documentation Change
description: A request to edit/add/fix the community docs, api docs, guides, etc.
title: '[Docs]: '
labels: ['Type: documentation', 'Status: Needs Triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our docs!

        ![Documentation beats conversation!](https://media.tenor.co/images/79a44a3e45d1d456754832d78393395f/tenor.gif)

        **Please note:** If this is a question or you're not sure about something, please consider using [our discussion board](https://github.com/Virtual-Coffee/virtualcoffee.io/discussions) to ask a question or get some help!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the change you're considering.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: context-for-change
    attributes:
      label: Context for documentation change
      description: Explain here the conditions which led you to write this issue.
      placeholder: 'For example: Noticed unclear explanation of build and install. Encountered a few issues attempting it myself. This could confuse other contributors.'
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Explain what solution and solution criteria looks like
      placeholder: 'For example: Contributing needs an expanded section detailing how to install and a section for troubleshooting'
    validations:
      required: false
  - type: textarea
    id: resources
    attributes:
      label: Resources that can help
      description: |
        Include any documents, images, tutorials, etc that can help the problem be solved.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
        For example:
        - Here's a link to a stack overflow thread describing the issue.
        - Here's a screenshot of the error and how people can work through it.
    validations:
      required: false
  - type: textarea
    id: collaborators
    attributes:
      label: Collaborators
      description: |
        Include anyone who may be relevant to the discussion by mentioning them via their github user name.
      placeholder: |
        For example:
        `@tkshill` do you have any thoughts here?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)
      options:
        - label: I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community
          required: true
