import fs from 'fs';
import path from 'path';

/**
 * Records the aspect ratio of every illustration in `public/assets/svg`.
 *
 * `UndrawIllustration` renders through `next/image`, which needs concrete
 * dimensions. Reading the files at render time is not an option for a
 * component that ships to the client, so the ratios are baked into
 * `src/data/undrawAspectRatios.ts` here instead. Generating it keeps the map
 * from drifting: it previously covered barely half the files, and a page whose
 * frontmatter named a missing one crashed the production build.
 */

const svgDir = path.join('.', 'public', 'assets', 'svg');
const outFile = path.join('.', 'src', 'data', 'undrawAspectRatios.ts');

/** Enough of the file to reach the opening `<svg>` tag. */
const HEAD_BYTES = 4000;

/** Drops a trailing `.0` and any leading zeros, so `955.00` reads as `955`. */
function formatNumber(value: string) {
	return String(Number(value));
}

function readAspectRatio(file: string) {
	const head = fs.readFileSync(file, 'utf8').slice(0, HEAD_BYTES);

	const viewBox = head.match(/viewBox\s*=\s*"([^"]+)"/);
	if (viewBox) {
		const parts = viewBox[1].replace(/,/g, ' ').split(/\s+/).filter(Boolean);
		if (parts.length === 4) {
			return `${formatNumber(parts[2])} / ${formatNumber(parts[3])}`;
		}
	}

	// A handful of exports set width/height instead of a viewBox.
	const width = head.match(/\bwidth\s*=\s*"([\d.]+)/);
	const height = head.match(/\bheight\s*=\s*"([\d.]+)/);
	if (width && height) {
		return `${formatNumber(width[1])} / ${formatNumber(height[1])}`;
	}

	return null;
}

const entries: string[] = [];
const skipped: string[] = [];

fs.readdirSync(svgDir)
	.filter((name) => name.endsWith('.svg'))
	.sort()
	.forEach((name) => {
		const aspectRatio = readAspectRatio(path.join(svgDir, name));
		if (aspectRatio) {
			entries.push(`\t${name.replace(/\.svg$/, '')}: '${aspectRatio}',`);
		} else {
			skipped.push(name);
		}
	});

if (skipped.length) {
	console.warn(
		`No viewBox or width/height found, skipping: ${skipped.join(', ')}`,
	);
}

fs.writeFileSync(
	outFile,
	`// Generated by scripts/loadUndrawAspectRatios.ts - do not edit.
// Run \`pnpm build-undraw-ratios\` after adding an SVG to public/assets/svg.

/** \`width / height\` from each illustration's \`viewBox\`, for \`next/image\`. */
export const svgAspectRatios = {
${entries.join('\n')}
};
`,
	'utf8',
);

console.log(`Wrote ${entries.length} aspect ratios to ${outFile}`);
