import fs from 'fs';
import path from 'path';
import { extractRoutes, loadMdxDirectory } from '../src/util/loadMdx.server';

/**
 * Writes every URL the `/resources` route serves to
 * `src/data/resourcePaths.ts` as a `ResourcePath` union.
 *
 * `resources/[[...slug]]` types as `/resources/${string}`, so typedRoutes
 * cannot tell a typo from a page. `resourceHref()` takes a `ResourcePath`
 * instead; it comes from the same `loadMdxDirectory` + `extractRoutes` the
 * resources page and the sitemap use, so the three cannot disagree.
 */

const outFile = path.join('.', 'src', 'data', 'resourcePaths.ts');

async function main() {
	const files = await loadMdxDirectory({ baseDirectory: 'content/resources' });
	const paths = [
		'/resources',
		...extractRoutes(files, 'content/resources/')
			.filter(Boolean)
			.map((slug) => `/resources/${slug}`),
	]
		.filter((p, i, all) => all.indexOf(p) === i)
		.sort();

	fs.writeFileSync(
		outFile,
		`// Generated by scripts/loadResourcePaths.ts - do not edit.
// Run \`pnpm build-resource-paths\` after adding or moving a file in src/content/resources.

export const resourcePaths = [
${paths.map((p) => `\t'${p}',`).join('\n')}
] as const;

/** Every URL the \`/resources\` route serves. */
export type ResourcePath = (typeof resourcePaths)[number];
`,
		'utf8',
	);

	console.log(`Wrote ${paths.length} resource paths to ${outFile}`);
}

void main();
