const teams = {
	'Community Maintainer': ['BekahHW', 'tkshill'],

	'Org Maintainer': ['danieltott', 'BekahHW'],
	'Lunch & Learn Coordinator': ['shelleymcq'],
	'Coffee Table Groups Coordinator': ['abbeyperini'],
	'Maintainer Emeritus': ['saramccombs'],
	'Room Leader': [
		'abbeyperini',
		'AlexVCS',
		'andreamartz',
		'aurelieverrot',
		'BogDAAAMN',
		'davidalpert',
		'glenmccallumcan',
		'jdwilkin4',
		'JoeKarow',
		'juliaseid',
		'mrsantons',
		'marktnoonan',
		'meg-gutshall',
		'nickytonline',
		'jamesrascal',
		'shiftyp',
		'SuzeShardlow',
		'teezzan',
		'tomcudd',
		'LincolnFleet',
		'needcaffeine',
		'saramccombs',
	],

	Notetaker: [
		'abbeyperini',
		'andreamartz',
		'aurelieverrot',
		'davidalpert',
		'aureliefomum',
		'glenmccallumcan',
		'jdwilkin4',
		'mrsantons',
		'meg-gutshall',
		'nickytonline',
		'Rafi993',
		'jamesrascal',
		'shiftyp',
		'SuzeShardlow',
		'teezzan',
		'tomcudd',
		'LincolnFleet',
		'needcaffeine',
		'YolandaHaynes',
		'SNikhill',
		'CuriousCurmudgeon',
	],

	'Monthly Challenge Team Lead': ['aurelieverrot', 'Andrew-Bush'],

	'Documentation Team Lead': ['adiati98'],
	'VC Advisor': [
		'adiati98',
		'davidalpert',
		'jdwilkin4',
		'meg-gutshall',
		'nickytonline',
		'SuzeShardlow',
		'tomcudd',
		'LincolnFleet',
		'rhdeck',
		'saramccombs',
	],

	'AV Team Lead': ['BogDAAAMN'],
	'Coffee Table Host': [
		'juliaseid',
		'mrsantons',
		'meg-gutshall',
		'LincolnFleet',
		'rhdeck',
		'kldickenson',
	],

	'VC Host': ['meg-gutshall', 'nickytonline', 'SuzeShardlow', 'saramccombs'],

	'VC MC': ['meg-gutshall', 'SuzeShardlow', 'saramccombs'],

	'Monthly Challenge Team': ['dominicduffin1', 'redapy', 'lsparlin'],
} as const;

export default teams;
