const teams = {
	'Community Maintainer': ['BekahHW', 'tkshill', 'juliaseid'],

	'Org Maintainer': ['danieltott', 'BekahHW'],
	'Lunch & Learn Coordinator': ['shelleymcq'],
	'Coffee Table Groups Coordinator': ['abbeyperini'],
	'Maintainer Emeritus': ['saramccombs'],
	'Room Leader': [
		'abbeyperini',
		'AlexVCS',
		'andreamartz',
		'aurelieverrot',
		'BogDAAAMN',
		'davidalpert',
		'glenmccallumcan',
		'jdwilkin4',
		'JoeKarow',
		'juliaseid',
		'mrsantons',
		'marktnoonan',
		'meg-gutshall',
		'nickytonline',
		'jamesrascal',
		'shiftyp',
		'SuzeShardlow',
		'teezzan',
		'tomcudd',
		'LincolnFleet',
		'needcaffeine',
		'saramccombs',
		'derekjj',
	],

	Notetaker: [
		'abbeyperini',
		'andreamartz',
		'aurelieverrot',
		'davidalpert',
		'aureliefomum',
		'glenmccallumcan',
		'jdwilkin4',
		'mrsantons',
		'meg-gutshall',
		'nickytonline',
		'Rafi993',
		'jamesrascal',
		'shiftyp',
		'SuzeShardlow',
		'teezzan',
		'tomcudd',
		'LincolnFleet',
		'needcaffeine',
		'YolandaHaynes',
		'SNikhill',
		'CuriousCurmudgeon',
		'sadiejay',
		'derekjj',
	],

	'Monthly Challenge Team Lead': ['adiati98', 'dominicduffin1'],

	'Documentation Team Lead': ['adiati98'],
	'VC Advisor': [
		'adiati98',
		'davidalpert',
		'jdwilkin4',
		'meg-gutshall',
		'nickytonline',
		'SuzeShardlow',
		'tomcudd',
		'LincolnFleet',
		'rhdeck',
		'saramccombs',
	],

	'AV Team Lead': ['BogDAAAMN'],
	'Coffee Table Host': [
		'juliaseid',
		'mrsantons',
		'meg-gutshall',
		'LincolnFleet',
		'rhdeck',
		'kldickenson',
	],

	'VC Host': ['meg-gutshall', 'nickytonline', 'SuzeShardlow', 'saramccombs'],

	'VC MC': ['meg-gutshall', 'SuzeShardlow', 'saramccombs'],

	'Monthly Challenge Team': ['redapy', 'lsparlin'],
} as const;

export default teams;
